### PR TITLE
indicator-doom-cpu: include plain GTK support

### PR DESCRIPTION
**Pull request by thypon**

### CODE REVIEW

**Comment by ebruck** [comment]
Thanks for this!

Just tried it, but ran into an error:

['(C) 2014 Edward G. Bruck <ed.bruck1@gmail.com>', '(C) 2017 Andrea Brancaleoni <miwaxe@gmail.com>']
./indicator-doom-cpu:29: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GObject, GdkPixbuf
./indicator-doom-cpu:32: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as AppIndicator
Traceback (most recent call last):
  File "./indicator-doom-cpu", line 185, in <module>
    DOOMCPUIndicator().run()
  File "./indicator-doom-cpu", line 157, in __init__
    AbstractDOOMCPUIndicator.__init__(self)
  File "./indicator-doom-cpu", line 104, in __init__
    self.build_menu()
  File "./indicator-doom-cpu", line 164, in build_menu
    self.app_indicator.set_menu(menu)
AttributeError: 'DOOMCPUIndicator' object has no attribute 'app_indicator'

**Comment by thypon** [comment]
The last commit should fix the code.

**Comment by ebruck** [comment]
Still a problem:

Traceback (most recent call last):
  File "./indicator-doom-cpu", line 185, in <module>
    DOOMCPUIndicator().run()
  File "./indicator-doom-cpu", line 159, in __init__
    AbstractDOOMCPUIndicator.__init__(self)
  File "./indicator-doom-cpu", line 104, in __init__
    self.build_menu()
  File "./indicator-doom-cpu", line 164, in build_menu
    self.app_indicator.set_menu(menu)
NameError: global name 'menu' is not defined

**Comment by thypon** [comment]
Sorry can't test AppIndicator version directly. This should fix

**Comment by ebruck** [comment]
Looks good! I have a few minor changes I've been wanting to make and then I'll release a new version.

**Comment by thypon** [comment]
Take your time

**Comment by thypon** [comment]
How is going with this PR?

**Comment by ebruck** [comment]
Sorry about that. It had totally slipped my mind.
I'll get to it sometime today or tomorrow.

**Pull request merged**
